/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Dashboard: () => import('#controllers/dashboard_controller'),
  DashboardProjectCategories: () => import('#controllers/dashboard_project_categories_controller'),
  DashboardProjects: () => import('#controllers/dashboard_projects_controller'),
  Images: () => import('#controllers/images_controller'),
  ProjectCategories: () => import('#controllers/project_categories_controller'),
  Projects: () => import('#controllers/projects_controller'),
  ProjectsPage: () => import('#controllers/projects_page_controller'),
  Session: () => import('#controllers/session_controller'),
}
